### ISSUE TITLE
Post-up and post-down for firewall rules?

### ISSUE THREAD

**Issue by axelsimon** [naggie/dsnet#16]
Hi,
I may have missed something in the docs, but is there a way to specify either a command or a script to run when starting the wg interface with dsnet, similar to the PostUp and PostDown fields in the wireguard config files?

I'm thinking on the server side, when looking at a basic centralised VPN set-up with multiple clients.

**Comment by naggie** [comment]
There really should be, I'll implement this when I get time.

**Comment by fs111** [comment]
This would be a great addition. What is required to make that work? I took a quick look at the code but could not figure out where that would fit in.

**Comment by naggie** [comment]
I'd suggest in the `dsnet up` and `dsnet down` commands -- implemented in the files named as such. I think it should be passed through a shell too, so slightly more complicated commands can be used. `/bin/bash` is on nearly every system (aside from FreeBSD by default, so we should fall back to `/bin/sh` in that case, or just use `/bin/sh` which is commonly dash or bash)
