### ISSUE TITLE
Non-interactive use

### ISSUE THREAD

**Issue by viq** [naggie/dsnet#17]
This could be great to automate setting up configuration for new endpoints, but from what I saw it only works in interactive mode, where it asks you things, and then uses those answers to generate config. Is there a way to run it from a script, without terminal?

**Comment by naggie** [comment]
Hi!

I agree -- there isn't currently but I think the commands should be modified to parse the command line such that it's possible to do in place of the interactive prompt. It would also make more advanced workflows available such as specifying the peer public key or IP.

If you're willing I'd definitely like a PR for this, possibly using cobra or flags.

Alternatively it's possible to use dsnet like a go library.

**Comment by xsteadfastx** [comment]
starting to work a little on it:

https://github.com/xsteadfastx/dsnet/tree/cobra

feedback is really welcome!

**Comment by xsteadfastx** [comment]
cant this be closed? my PR is merged and dnset can now be used in a non-interactive way.

**Comment by naggie** [comment]
Yes, thanks for the work :)
