### ISSUE TITLE
ARMv7 issue

### ISSUE THREAD

**Issue by amarc** [naggie/dsnet#26]
Hello,

is dsnet tested to be working on RPi 4 ? 

Currently I have this kernel: Linux wg 5.4.77-1-ARCH #1 SMP PREEMPT Tue Nov 17 20:56:33 UTC 2020 armv7l GNU/Linux

and upon dsnet init I get:

bash: /usr/local/bin/dsnet: cannot execute binary file: Exec format error

Not sure if this is because v7 is not supported or it could be something else..

Never had this issue on x86

**Comment by amarc** [comment]
Edit:

forget about above, I just pulled amd64 instead of ARM binary :/

Sorry about that..

**Comment by naggie** [comment]
Oh, no problem 👍

**Comment by amarc** [comment]
Sorry, it seem's it's not going well again. Upon dsnet init I get this:

Could not add interface 'wg' (operation not supported)

wg is my interface name in .json config.


This is on RPi 4 and Arch Linux ARM. 

Could it be binaries are not supported on other distros other than Debian/Ubuntu/etc.. ?

**Comment by amarc** [comment]
Can confirm this does not work on Raspian either (without LXC part). Same error message

**Comment by Write** [comment]
Work great on my RPi4 4GB with Ubuntu 20.04.1 LTS

**Comment by naggie** [comment]
@amarc what kernel are you using? Is it an older one that requires a wireguard kernel module?

**Comment by amarc** [comment]
@naggie whichever is on *latest* raspbian.. can't tell now as I reflashed my SD Card with Ubuntu 20.04 and it works without issues.

It could be that.. Debian is known to be couple steps behind

**Comment by naggie** [comment]
Ah, IIRC you'll have to compile a wireguard kernel module and load it for raspbian.
