### ISSUE TITLE
Use hostname instead IP 

### ISSUE THREAD

**Issue by amarc** [naggie/dsnet#28]
Hello,

is it possible to workaround dynamic IP's by entering some (updated with ddclient) domain name in "ExternalIP" instead of actual IPv4 ?

**Comment by naggie** [comment]
Not right now, `ExternalIP` is parsed as an IP. For a workaround, the generated client config could be edited.

I think as a result of https://github.com/naggie/dsnet/issues/27 there will be a solution to this soon.

**Comment by amarc** [comment]
Great, thanks.

My workaround is to have local IP listed there since I am already doing port forward on that IP. Than on client I update Endpoint to use hostname instead that local IP

**Comment by naggie** [comment]
Implemented in 0.4 with `ExternalHost` which has precedence over `ExternalIP` and `ExternalIP6`
