### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by botto** [naggie/dsnet#45]
Just opening this here for logo ideas. I'm no designer/icon kind of person, but would love if someone had ideas and or talent they would love to share.

Ideas I've had for logos so far:
- A hash/net style (to represent ds**net**)
- Three nodes connected in a v shape

**Comment by naggie** [comment]
I could get one made on Fiverr I guess.

**Comment by mirorauhala** [comment]
tell me what you think
<img width="830" alt="FLAT_ Logo with black background" src="https://user-images.githubusercontent.com/4082806/185443821-c53848d7-6212-4d69-abcd-ebf218e770f8.png">
<img width="972" alt="Frame 6" src="https://user-images.githubusercontent.com/4082806/185444650-183da450-227b-43d6-97d5-bf9f296d1fd1.png">

**Comment by naggie** [comment]
Wow that's really cool!! Thanks @mirorauhala

**Comment by mirorauhala** [comment]
I'll make a couple of tweaks and send you the vectors tomorrow.

**Comment by botto** [comment]
They look great!

**Comment by mirorauhala** [comment]
Here is a zip containing some exported SVGs as well as the [Figma](https://www.figma.com/) design document you can import to make changes.

[dsnet-logo.zip](https://github.com/naggie/dsnet/files/9383158/dsnet-logo.zip)

**Comment by naggie** [comment]
Done. Thanks again!
