### ISSUE TITLE
Add a packages section to the README

### ISSUE THREAD

**Issue by f-koehler** [naggie/dsnet#49]
I just packaged `dsnet` for ArchLinux in the [AUR](https://aur.archlinux.org/packages/dsnet-git/). This builds from the main branch.
Maybe at some point it would be nice to add a section to `README.md` where we list all the available packaged versions of `dsnet` for various distributions.

I know due to `go` the binaries are very portable but sometimes its nice to just install it via a package manager and keep it up to date this way. I have not yet checked if there exist packages for other distributions.

**Comment by naggie** [comment]
Thanks for packaging it, I'll add a repology badge like I did for dstask. I recommend that you build from the latest release tag instead of master, however, as there's no guarantee that master is functional.

**Comment by f-koehler** [comment]
What a coincidence, I just added a package [`dsnet`](https://aur.archlinux.org/packages/dsnet/) that build from the latest tag.
However, for Archlinux it is quite common to have these options available. But of course you are correct in stating that build from the main branch might fail.

A repology badge is a nice idea.

**Comment by naggie** [comment]
Great -- I've added a badge. Thanks again.
