### ISSUE TITLE
Launch at boot ?

### ISSUE THREAD

**Issue by Write** [naggie/dsnet#5]
Hi,

I discovered this tools on HN and decided to move all my current config on it.
Everything is working great and smooth. Unfortunately my old /etc/wireguard/wg0.conf is up and running at boot, how can i set it to launch 'dsnet up' at boot instead ?

Thanks.

**Comment by naggie** [comment]
Assuming you're using a `wq-quick` with `systemctl` integration, this will do it: 


`
sudo systemctl stop wg-quick@wg0
sudo systemctl disable wg-quick@wg0

sudo systemctl enable wg-quick@dsnet
sudo systemctl start wg-quick@dsnet
`

**Comment by Write** [comment]
Thanks, it work great !
I had to enable the service before daemon-reload with `sudo systemctl enable dsnet.service`

Have a great day

**Comment by naggie** [comment]
Excellent, you're welcome.
