### ISSUE TITLE
ListenPort limitation

### ISSUE THREAD

**Issue by toushin-taishi** [naggie/dsnet#57]
Hi. What are the ports that are allowed to be used in dsnetconfig.json?
I tried using known UDP ports (53,123,etc) but dnsnet errors out.

Due to some experiences ISP throttling wireguard traffic, there is a need to change the wireguard port to something that will not be throttled by ISP. 

Is this limitation in dsnet be considered in the next future releases?

Thanks and kind regards.

**Comment by naggie** [comment]
What error do you get? There's nothing inherent in dsnet that allows only certain ports.

**Comment by toushin-taishi** [comment]
Hello @naggie,

Thanks for the reply. The error I get when I tried the ports 53,123 and 500 is:

> Key: 'DsnetConfig.ListenPort' Error:Field validation for 'ListenPort' failed on the 'gte' tag

Using other ports such as 4500 or 1194 is fine.

Thanks and kind regards

**Comment by naggie** [comment]
I've fixed this in master -- the next release will contain the fix; in the mean time you can compile your own executable
