### ISSUE TITLE
Move Config File

### ISSUE THREAD

**Issue by djbusby** [naggie/dsnet#7]
Please move the config file, like `/etc/dsnet/server.json`

For when you add featues (inevitable).

I also have the case where I have many configs to use, so in one path by default is handy for me.

I plan to send PR when not on mobile.

**Comment by naggie** [comment]
I'll keep it where it is for the time being until a need arises.

Note that the project is deliberately limited in scope so there's no plan to add many signifiant more features; though I know someone who's making progress on a web GUI.

Thanks
Callan
