### ISSUE TITLE
Can't add networks

### ISSUE THREAD

**Issue by dakser** [naggie/dsnet#72]
Hi, I'm trying to add 0.0.0.0/0 in Networks but it doesn't work. (I've tried with    "Networks": "0.0.0.0/0",    "Networks": "[0.0.0.0/0]", "Networks": 0.0.0.0/0)
Do you have any advice? Thanks in advance.

**Comment by naggie** [comment]
It should be a list of CIDR strings, i.e.: `["172.18.2.0/24", "10.0.0.1/24"]` -- dsnet currently does nothing with these, but I plan on making it add routes soon.
