### ISSUE TITLE
dsnet up fails because default config doesn't populate the ReportFile field

### ISSUE THREAD

**Issue by axelsimon** [naggie/dsnet#85]
Full error:
`Key: 'DsnetConfig.ReportFile' Error:Field validation for 'ReportFile' failed on the 'required' tag - failed to load configuration file`
this is with dsnet v.0.7.2.

I'm pretty sure that field used to be filled with a default. In any case, simply making sure the config has something like:
```
    "ReportFile": "/tmp/dsnetreport.json",
```
is enough to stop dsnet from complaining and to issue `dsnet up` successfully.

**Comment by naggie** [comment]
Thanks @axelsimon  -- fixed in master. I'll cut a release soon
