### ISSUE TITLE
Is it possible to run without root?

### ISSUE THREAD

**Issue by bbigras** [naggie/dsnet#87]

**Comment by naggie** [comment]
It is! Use `setuid` root, with a `dsnet` group to decide who can run `dsnet`.

**Comment by bbigras** [comment]
Thank you for your quick reply. Sorry for my late one. :sweat_smile: 

I mean without any `root` rights.

I'm also wondering if there's a way to save to a custom folder instead of /etc/something.

It could be useful to have more than 1 "network".

**Comment by naggie** [comment]
I guess it could be added as an option or env var. 

Not possible, I think, unless there's a `setcap` that gives the right permissions
